import os
import json
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

def load_news():
    try:
        # Assuming run from root directory
        file_path = "summarized_news.json"
        
        # Fallback if in subdirectory
        if not os.path.exists(file_path):
             file_path = "../summarized_news.json"
             
        with open(file_path, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        print("[ERROR] summarized_news.json not found. Run app.py first.")
        return []

def format_email_body(articles):
    html = f"""
    <html>
    <head>
        <style>
            body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
            .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
            .header {{ background-color: #2c3e50; color: white; padding: 15px; text-align: center; border-radius: 5px 5px 0 0; }}
            .article {{ border: 1px solid #ddd; border-top: none; padding: 15px; margin-bottom: 0; background-color: #fff; }}
            .article:first-of-type {{ border-top: 1px solid #ddd; }}
            .source {{ color: #e74c3c; font-weight: bold; font-size: 0.9em; }}
            .title {{ color: #2c3e50; font-size: 1.2em; margin: 5px 0; font-weight: bold; }}
            .summary {{ color: #555; background-color: #f9f9f9; padding: 10px; border-left: 4px solid #3498db; border-radius: 3px; }}
            .footer {{ text-align: center; font-size: 0.8em; color: #888; margin-top: 20px; padding: 10px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h2>Daily News Brief</h2>
                <p>{datetime.now().strftime('%B %d, %Y')}</p>
            </div>
    """

    for article in articles:
        source = article.get("source", "Unknown Source")
        title = article.get("title", "No Title")
        summary = article.get("summary", "No Summary Available").replace("\n", "<br>")

        html += f"""
            <div class="article">
                <div class="source">{source}</div>
                <div class="title">{title}</div>
                <div class="summary">{summary}</div>
            </div>
        """

    html += """
            <div class="footer">
                <p>Generated by AI News Agent</p>
            </div>
        </div>
    </body>
    </html>
    """
    return html

def send_email(subject, body_html):
    sender_email = os.environ.get("GMAIL_USER")
    sender_password = os.environ.get("GMAIL_APP_PASSWORD")
    recipients_str = os.environ.get("RECIPIENT_EMAILS")

    if not all([sender_email, sender_password, recipients_str]):
        print("[ERROR] Missing email configuration in .env file.")
        print("Please check GMAIL_USER, GMAIL_APP_PASSWORD, and RECIPIENT_EMAILS.")
        return

    recipients = [email.strip() for email in recipients_str.split(",")]

    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = ", ".join(recipients)
    msg['Subject'] = subject

    msg.attach(MIMEText(body_html, 'html'))

    try:
        print("Connecting to Gmail SMTP...")
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(sender_email, sender_password)
            server.sendmail(sender_email, recipients, msg.as_string())
        print(f"Email sent successfully to: {', '.join(recipients)}")
    except Exception as e:
        print(f"[ERROR] Failed to send email: {e}")

def main():
    print(">>> Reading News Data...")
    articles = load_news()
    
    if not articles:
        print("No articles to send.")
        return

    print(f"Loaded {len(articles)} articles.")
    
    body_html = format_email_body(articles)
    subject = f"AI News Brief - {datetime.now().strftime('%d %b %Y')}"
    
    send_email(subject, body_html)

if __name__ == "__main__":
    main()
